"""Storage protocol + schema constants for control plane backends."""

from __future__ import annotations

from typing import Any, Protocol


class StoreProtocol(Protocol):
    def upsert_graph(self, graph_id: str, name: str, mermaid: str, skeleton: dict, *, tenant_id: str = "default") -> None: ...
    def get_graph(self, graph_id: str, *, tenant_id: str = "default") -> dict[str, Any] | None: ...
    def list_graphs(self, *, tenant_id: str = "default") -> list[dict[str, Any]]: ...
    def upsert_run(self, **fields: Any) -> None: ...
    def get_run(self, thread_id: str, *, tenant_id: str | None = None) -> dict[str, Any] | None: ...
    def list_runs(self, *, tenant_id: str = "default", status: str | None = None, limit: int = 200) -> list[dict[str, Any]]: ...
    def fleet_summary(self, *, tenant_id: str = "default") -> dict[str, int]: ...
    def put_checkpoint(self, cp: dict[str, Any]) -> None: ...
    def latest_checkpoint(self, thread_id: str) -> dict[str, Any] | None: ...
    def list_checkpoints(self, thread_id: str, *, limit: int = 50) -> list[dict[str, Any]]: ...
    def clear_checkpoints(self, thread_id: str) -> int: ...
    def ping(self) -> None: ...
    def append_event(self, **kwargs: Any) -> dict[str, Any]: ...
    def events_since(self, last_id: int = 0, *, tenant_id: str | None = None, limit: int = 500) -> list[dict[str, Any]]: ...
    def events_for_thread(self, thread_id: str, *, limit: int = 200) -> list[dict[str, Any]]: ...
    def add_alert(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_alerts(self, *, tenant_id: str = "default", open_only: bool = True, limit: int = 100) -> list[dict[str, Any]]: ...
    def ack_alert(self, alert_id: int, *, tenant_id: str = "default") -> None: ...
    def append_path_step(self, thread_id: str, node_id: str, *, tenant_id: str = "default", ts: float | None = None) -> None: ...
    def get_path(self, thread_id: str) -> list[str]: ...
    def record_metric(self, *, tenant_id: str, name: str, value: float, labels: dict | None = None, ts: float | None = None) -> None: ...
    def query_metrics(self, *, tenant_id: str, name: str | None = None, since_s: float = 3600) -> list[dict[str, Any]]: ...
    def metrics_rollup(self, *, tenant_id: str = "default") -> dict[str, Any]: ...
    def close(self) -> None: ...
